# Generated by Django 4.2.5 on 2023-09-16 20:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('tamanho', models.CharField(max_length=3)),
                ('preco_de_compra', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.categoria')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
    ]
