# Generated by Django 4.2.5 on 2023-10-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': [models.OrderBy(models.F('id'))]},
        ),
        migrations.AlterModelOptions(
            name='produtotamanho',
            options={'ordering': [models.OrderBy(models.F('id'))]},
        ),
        migrations.AlterModelOptions(
            name='tamanho',
            options={'ordering': [models.OrderBy(models.F('id'))]},
        ),
    ]
