# Generated by Django 4.2.5 on 2023-10-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_options_alter_produtotamanho_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtotamanho',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
